#!/usr/bin/env bash
open --hide /Applications/Utilities/XQuartz.app
/opt/X11/bin/xhost + localhost
/usr/local/bin/docker run --rm  -e DISPLAY=host.docker.internal:0 --net=host --volume=$HOME:/macOS \
   --volume=$HOME/quartus/root:/root/ --name=modelSim -d -ti quartus  /quartus/modelsim_ase/bin/vsim
  
